### ISSUE TITLE
broken Link

### ISSUE THREAD

**Issue by Rheinlaender** [RWTH-EBC/AixOCAT#20]
> Just stopping by to let us know about some issue you encountered with AixOCAT? Please feel free to delete all of this text and tell us what you think!

> If you want to suggest larger changes and/or adding new structures to AixOCAT, please make sure to briefly answer the following few questions. For more information on how to contribute to AixLib, see our [Wiki](https://github.com/RWTH-EBC/AixLib/wiki). Before submitting the issue, you can delete these first lines. Thanks for contributing!

## What is the problem?
 broken link on start page http://rwth-ebc.github.io/AixOCAT/

- ...

## Why do we want to solve it?

- hää, because it's broken

## How do we want to solve it?

- idk

**Comment by msc-d1s7fa1eza** [comment]
Fixed with https://github.com/RWTH-EBC/AixOCAT/commit/6671b51606640bfd6a81dea0cfa522867ab65743
