### ISSUE TITLE
Naming in example

### ISSUE THREAD

**Issue by msc-d1s7fa1eza** [RWTH-EBC/AixOCAT#26]
> Just stopping by to let us know about some issue you encountered with AixOCAT? Please feel free to delete all of this text and tell us what you think!

> If you want to suggest larger changes and/or adding new structures to AixOCAT, please make sure to briefly answer the following few questions. For more information on how to contribute to AixOCAT, see our [Wiki](https://github.com/RWTH-EBC/AixOCAT/wiki). Before submitting the issue, you can delete these first lines. Thanks for contributing!

## What is the problem?

- Naming in the example project

## Why do we want to solve it?

- Convention: Offer english version in the first place

## How do we want to solve it?

- Change german language used to english

**Comment by MatMers** [comment]
Solved with commit e405f3a
