### ISSUE TITLE
Documentation of heat pump example

### ISSUE THREAD

**Issue by msc-d1s7fa1eza** [RWTH-EBC/AixOCAT#28]
> Just stopping by to let us know about some issue you encountered with AixOCAT? Please feel free to delete all of this text and tell us what you think!

> If you want to suggest larger changes and/or adding new structures to AixOCAT, please make sure to briefly answer the following few questions. For more information on how to contribute to AixOCAT, see our [Wiki](https://github.com/RWTH-EBC/AixOCAT/wiki). Before submitting the issue, you can delete these first lines. Thanks for contributing!

## What is the problem?

- The heat pump example is not documented well.

## Why do we want to solve it?

- A proper documentation of usage and functionality would improve understanding relationships or using parts of the project.

## How do we want to solve it?

- Improve the documentation by adding visualizations and a textual description.

**Comment by katharinabr** [comment]
We'll delete the example.
