### ISSUE TITLE
BACnet example & documentation

### ISSUE THREAD

**Issue by ghost** [RWTH-EBC/AixOCAT#29]
Document BACnet connection to WILO pumps (including BACnet MS/TP to BACnet IP) and add clean example

**Comment by msc-d1s7fa1eza** [comment]
The example should contain both the general functions and interactions between different modules  and BACnet components or the utilization of libraries respectively as well as the definition and sending of BACnet data points.

**Comment by katharinabr** [comment]
We use the commercial BACnet-lib by Beckhoff thus this is not part of the AixOCAT.
