### ISSUE TITLE
uniqueNaming

### ISSUE THREAD

**Issue by MBaranskiEBC** [RWTH-EBC/AixOCAT#34]
## What is the issue/what feature do you want to develop?

- Ensure that all FBs in then lib are unique and cannot be confused with the names used in other libraries

## What is the current application?

- relevant for all applications

## What are the requirements?

- Consistent renaming of all FBs

## How do we want to solve it?

- I propose to use a prefix such as aixo

## Priority, deadline?

- Before next release

**Comment by katharinabr** [comment]
Ensure that all FBs in then lib are unique while implementing new ones.
