### ISSUE TITLE
Library installation link for TwinCAT3 not working

### ISSUE THREAD

**Issue by sagatowski** [RWTH-EBC/AixOCAT#40]
The library installation-link for TwinCAT3 in the README.MD-file is not working.

The right one should be:
https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/27021601982523403.html

**Comment by msc-d1s7fa1eza** [comment]
Thanks for pointing out!

I exchanged the link in both develop and master branch.
