### ISSUE TITLE
HiL3-GUI

### ISSUE THREAD

**Issue by janik-horst** [RWTH-EBC/AixOCAT#91]
Implementing changes from AixOCAT Fork Repo (https://git.rwth-aachen.de/andy.otto/aixocat-hil3-fork/-/tree/hil3_gui/dev), in order to use AixOCAT libary as HiL3-submodule

**Comment by StGoebel** [comment]
Hi @janik-horst it's not clear to me, what you want to change within this library. 
Could you describe the changes in more detail? We do not want to add complete GUIs from our test benches to this lib.
